### ISSUE TITLE
feat: calculate number of items on a page

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/uis-frontend#37]
fix this

![Image](https://user-images.githubusercontent.com/81484108/230785199-72a630e6-52d4-417d-8fc8-48cab78e16ed.png)

![Image](https://user-images.githubusercontent.com/81484108/230785211-3c208209-8230-4b3e-afdf-de13554a5e92.png)

also 

![Image](https://user-images.githubusercontent.com/81484108/231551941-e782cfa6-151e-41b2-adda-81ba80f1105c.png)

**Comment by tinmn9088** [comment]
See 3fe8e84ea71b67b8ddac999932c8dd48d867265a.
