### ISSUE TITLE
fix(auth): authentication bug

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/uis-frontend#58]
![Image](https://user-images.githubusercontent.com/81484108/234941087-bf9eef9f-792c-4628-ae2b-957344388ccc.png)

steps to reproduce
1) go to any module from academic without login

**Comment by fenix23707** [comment]
![Image](https://user-images.githubusercontent.com/81484108/235219154-f9d84e7b-bcb3-4da0-8f99-9910e10c473d.png)

**Comment by tinmn9088** [comment]
Call `AuthService.logout()` when session expired.

**Comment by tinmn9088** [comment]
See 77dd9abe63686eadae4e4409ffed66937192a044.
