### ISSUE TITLE
feat(user): more detailed error message

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/uis-frontend#61]
i have not idea why i can't create a user
![Image](https://user-images.githubusercontent.com/81484108/234955207-c369c85c-b5ac-483a-808d-fb68e5e74e1c.png)

**Comment by fenix23707** [comment]
add explain message on each field or mb use message from backend if it's good in that case

**Comment by fenix23707** [comment]
In case it's an error 

![Image](https://user-images.githubusercontent.com/81484108/234955526-2f568fc1-05b9-4457-afa5-d962dd24ba2d.png)

**Comment by tinmn9088** [comment]
See a761b43d6973035dd9fac7d61a592258285d492f.
