### ISSUE TITLE
feat(discipline): show category name instead of id

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/uis-frontend#64]
![Image](https://user-images.githubusercontent.com/81484108/234956827-b6a8c3ea-7454-4df1-91cf-b7b678fe85cc.png)

**Comment by fenix23707** [comment]
same here 

![Image](https://user-images.githubusercontent.com/81484108/235223117-24474375-75d8-42d3-aa0d-dad04d18bb6d.png)

**Comment by fenix23707** [comment]
also i would make these fields clickable to see info about them

**Comment by fenix23707** [comment]
Same here

![Image](https://github.com/tinmn9088/uis-frontend/assets/81484108/e9b91c13-a077-4fa5-99be-f1c26a25b1b6)

**Comment by fenix23707** [comment]
I have no idea what we can do here but i don't wanna see meaningless numbers

**Comment by tinmn9088** [comment]
See d5ceb8028d63b6be10a22d69a3b1929ee93fda66, a5194451a587cbec2b14a7928ab122ca074b6fb4.
