### ISSUE TITLE
fix(specialization): localization is not working

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/uis-frontend#65]
![Image](https://user-images.githubusercontent.com/81484108/234957209-5c266b19-5c75-4173-950e-229a5a1cbd88.png)

**Comment by tinmn9088** [comment]
Try call TranslateService after expand.

**Comment by tinmn9088** [comment]
Need to add localization.



![Image](https://user-images.githubusercontent.com/67731464/235316005-2341666a-52e4-448d-b637-ba989bc5885d.png)

**Comment by tinmn9088** [comment]
See 98d74c7d6f9bc1bd51824a48f8617787bdd18dd1.
