### ISSUE TITLE
fix(curriculum): currculum discipline validation error

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/uis-frontend#74]
The message which I sent is more descriptive than what i see on ui + I still can send request without specify all fields

![Image](https://user-images.githubusercontent.com/81484108/237470596-917104c7-6f1f-4807-aabb-02fa9fad317e.png)

**Comment by fenix23707** [comment]
Mb i should allow zero hours

**Comment by fenix23707** [comment]
If you think so create a story for me

**Comment by tinmn9088** [comment]
See aab4f781f2c2c0b3ef0154da68202135618d1ca7.
