### ISSUE TITLE
fix: permission handling

### ISSUE THREAD

**Issue by fenix23707** [tinmn9088/uis-frontend#79]
I have an user with specializaiton full access and discipline search and get but when i loged in as this user i saw just specialization 
make sure that user can see all pages regarding his permissions 
![Image](https://user-images.githubusercontent.com/81484108/237473844-929ec3e1-eb8e-47ed-a173-b84ad05a26b5.png)

**Comment by fenix23707** [comment]
The same with permission module
And i belive with all modules so check please

**Comment by fenix23707** [comment]
be very carrefully because looks like there are a lot of bugs with this. And i can't check most of them due to it's works very bad

**Comment by tinmn9088** [comment]
See 7f5d635f45f37d80fe1177c25b09851faabb2769.

**Comment by tinmn9088** [comment]
See 60b33f5fc045a4e1aa6d3a2a5641bda5ab03e4b6, 0b9be5e0279ee3e7f05cbfa49b813bca7347c243, 97000f5169d7630666db783fa52af90d2e8666f5, acdb3ad6fcdf30295d51421de42374d35f5df3e1.
